"""Generate INDEX.org from literate-org.org.

For every section that owns a Python module (declares :LITERATE_ORG_MODULE:),
emit a row showing module name, heading, line, tangle path, and CUSTOM_ID.

Why: gives AI agents and humans a single map of "where does module X
live in the master file". Avoids ambiguous heading-text searches — see
~/.claude/rules/emacs-agent/search-by-custom-id-not-heading.md.

Output is deterministic; commit INDEX.org alongside literate-org.org.
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path

DEFAULT_TARGET = Path("literate-org.org")
DEFAULT_OUTPUT = Path("INDEX.org")

HEADING_RE = re.compile(r"^(\*+)\s+(.*?)\s*$")
PROP_LINE_RE = re.compile(r"^\s*:([\w-]+):\s*(.*?)\s*$")
PROP_END_RE = re.compile(r"^\s*:END:\s*$", re.IGNORECASE)
PROP_BEGIN_RE = re.compile(r"^\s*:PROPERTIES:\s*$", re.IGNORECASE)
HEADER_ARGS_TANGLE_RE = re.compile(r":tangle\s+(\S+)")


@dataclass
class Entry:
    line: int
    depth: int
    heading: str
    module: str
    tangle: str
    custom_id: str


def parse(path: Path) -> list[Entry]:
    lines = path.read_text(encoding="utf-8").splitlines()
    entries: list[Entry] = []
    i = 0
    while i < len(lines):
        m = HEADING_RE.match(lines[i])
        if not m:
            i += 1
            continue
        depth = len(m.group(1))
        heading = re.sub(r"\s*:[\w:]+:\s*$", "", m.group(2)).strip()
        lineno = i + 1
        props = read_properties(lines, i + 1)
        module = props.get("LITERATE_ORG_MODULE", "")
        custom_id = props.get("CUSTOM_ID", "")
        header_args = props.get("header-args", "")
        tangle_match = HEADER_ARGS_TANGLE_RE.search(header_args)
        tangle = tangle_match.group(1) if tangle_match else ""
        if module:
            entries.append(
                Entry(
                    line=lineno,
                    depth=depth,
                    heading=heading,
                    module=module,
                    tangle=tangle,
                    custom_id=custom_id,
                )
            )
        i += 1
    return entries


def read_properties(lines: list[str], start: int) -> dict[str, str]:
    """Read the :PROPERTIES: ... :END: drawer that immediately follows a
    heading, if any. Returns empty dict if no drawer is present.
    """
    props: dict[str, str] = {}
    if start >= len(lines):
        return props
    if not PROP_BEGIN_RE.match(lines[start]):
        return props
    j = start + 1
    while j < len(lines) and not PROP_END_RE.match(lines[j]):
        m = PROP_LINE_RE.match(lines[j])
        if m:
            props[m.group(1)] = m.group(2)
        j += 1
    return props


def render(entries: list[Entry], source: Path) -> str:
    lines = [
        "#+TITLE: literate-org Module Index",
        "#+OPTIONS: toc:nil num:nil",
        "",
        f"Generated by =scripts/build_index.py= from ={source}=. Do not edit by hand.",
        "",
        "| Module | Heading | Line | Tangle | CUSTOM_ID |",
        "|--------+---------+------+--------+-----------|",
    ]
    for e in sorted(entries, key=lambda x: x.module):
        link = f"[[file:{source}::{e.line}][{e.heading}]]"
        lines.append(
            f"| ={e.module}= | {link} | {e.line} | ={e.tangle}= | ={e.custom_id}= |"
        )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    target = Path(argv[1]) if len(argv) > 1 else DEFAULT_TARGET
    output = Path(argv[2]) if len(argv) > 2 else DEFAULT_OUTPUT
    if not target.exists():
        print(f"build_index: {target} not found", file=sys.stderr)
        return 1
    entries = parse(target)
    output.write_text(render(entries, target), encoding="utf-8")
    print(f"build_index: wrote {len(entries)} entries to {output}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
