# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/literate-python',
                'doc_host': 'https://jingtaozf.github.io',
                'git_url': 'https://github.com/jingtaozf/literate-python',
                'lib_path': 'literate_python'},
  'syms': {'literate_python.core': {'literate_python.core.foo': ('core.html#foo', 'literate_python/core.py')}}}
