#!/usr/bin/env bash
# PreToolUse hook: reject Edit/Write/MultiEdit on tangled .py files.
#
# Reads the Claude Code tool call payload from stdin (JSON). If the tool
# is Edit/Write/MultiEdit and the target path is inside literate_python/,
# we exit 2 with a stderr message — Claude Code surfaces stderr to the
# agent and treats exit 2 as a blocking error.
#
# Why: literate-org.org is the single source of truth for the maintainer.
# Tangled .py output is regenerated and would silently overwrite direct
# edits. Teammates who don't use Org are not affected — this hook only
# runs in the maintainer's Claude Code session.

set -euo pipefail

payload=$(cat)

# Extract fields with python (already a project dependency).
read -r tool_name file_path <<<"$(python3 - "$payload" <<'PY'
import json, sys
data = json.loads(sys.argv[1])
tool = data.get("tool_name", "")
inp  = data.get("tool_input", {})
path = inp.get("file_path", "") or ""
print(tool, path)
PY
)"

case "$tool_name" in
  Edit|Write|MultiEdit) ;;
  *) exit 0 ;;
esac

# Match anything under literate_python/ ending in .py.
case "$file_path" in
  */literate_python/*.py|literate_python/*.py)
    cat >&2 <<EOF
Refusing to edit $file_path: this file is tangled output from
literate-org.org (the project's literate-programming source of truth).

Edit the corresponding section in literate-org.org instead, then
re-tangle. The org section is identified by its :LITERATE_ORG_MODULE:
property — locate it however you prefer (grep, ripgrep, Emacs, the
INDEX.org generated by \`make index\`, etc.).

If you are intentionally hand-editing the .py for a non-LP reason
(team handoff, third-party patch), invoke this edit with the hook
disabled or commit directly without the agent.
EOF
    exit 2
    ;;
esac

exit 0
